openapi: 3.0.1
info:
  title: '@jupiterone/graph-mimecast'
  description: A JupiterOne Integration for ingesting data from Mimecast
  x-cortex-git:
    github:
      repository: JupiterOne/graph-mimecast
  x-cortex-owners:
    - type: group
      name: JupiterOne/integrations
  x-cortex-service-groups: tier-4
  x-cortex-tag: '@jupiterone/graph-mimecast'
